version: "3"
services:
  nodejsapi:
    image: gcr.io/avian-pact-231312/nodejs-api:latest
    # deploy:
    #   replicas: 5
    #   resources:
    #     limits:
    #       cpus: "0.1"
    #       memory: 50M
    #   restart_policy:
    #     condition: on-failure
    ports:
      - "4000:8080"
    networks:
      - nodejsapinet
  angular:
    image: gcr.io/avian-pact-231312/angular:latest
    # deploy:
    #   replicas: 5
    #   resources:
    #     limits:
    #       cpus: "0.1"
    #       memory: 50M
    #   restart_policy:
    #     condition: on-failure
    ports:
      - "4200:8080"
    networks:
      - angularnet
networks:
  nodejsapinet:
  angularnet:
